### ISSUE TITLE
Incorrect device handle in multi-camera configuration

### ISSUE THREAD

**Issue by oroygit** [TheImagingSource/tcam-firmware-update#1]
When multiple TIS cameras of the same type are connected (same vendor ID, same product ID), the device handle stored in the object returned by the ```UsbHandler::open_camera``` function corresponds to the first detected camera, not the camera with the requested serial number. The reason is that the device handle is retrieved in ```UsbCamera::open``` using a call to ```libusb_open_device_with_vid_pid``` instead of enumerating the connected devices and selecting the one with the correct serial number (see, e.g., https://libusb.sourceforge.io/api-1.0/group__libusb__dev.html#ga10d67e6f1e32d17c33d93ae04617392e).

Since the device handle is incorrect, e.g., downloading firmware, or querying firmware version will be performed on the wrong device.

See attached path file for suggested update to UsbCamera.cpp to fix the issue (apply using patch command). The main fix is in the ```open``` function. The rest of the modifications are mostly formatting differences. 

[open_device_fix.txt](https://github.com/TheImagingSource/tcam-firmware-update/files/9434920/open_device_fix.txt)

**Comment by TIS-Edgar** [comment]
Thank you for the patch.
I took the liberty of cleaning that commit up.
d1a6df0 implements your changes. 

Please keep in mind that we still recommend to only have one camera attached when writing firmware updates, just to be safe.
