### ISSUE TITLE
Celestron NexImage Burst C - Firmware 

### ISSUE THREAD

**Issue by girgine** [TheImagingSource/tcam-firmware-update#2]
Hi,
I recently updated the firmware for Celestron NexImage Burst C with the USB2 Firmware - [dmk42ue03_4001_uvc.euvc]

Astronomy programs I use reporting that the camera supports only B&W - Is there a firmware that enables the color mode? If not, can I get the original firmware that was shipped with the camera?

Thank you
Eg

**Comment by TIS-Stefan** [comment]
Hi

I suppose, you use the wrong firmware. The correct Linux firmware is [dfk42uc03_3014.euvc](https://github.com/TheImagingSource/tcam-firmware-update/blob/master/firmware/usb2/dfk42uc03_3014.euvc) . Not the "UE" variant.

Stefan

**Comment by girgine** [comment]
Thanks Stefan, 

I am using AstroDMX software v2.49 running raspberry 10 (buster). When I use the firmware dfk42uc03_3014 , astroDMX stucks at the beginning with the message "Initialising, please wait…" , the firmware i tried "4001" doesn't have the issue and it works. (but I understand it is monochrome)

The problem I am having is mentioned here:
https://www.astrodmx-capture.org.uk/astrodmx-technical-help-for-linux/

in the section titled ZWO USB2 Camera Issues.

Looks like might be the packet size problem which can be solved by the firmware that works?

Hope this helps,
Thanks - Eren

**Comment by TIS-Stefan** [comment]
Hello 
It seems, I mixed two camera models, thus use the firmware version 4001, if this gives images. 
I found firmware version 3006, which works in Linux with colors:
[dfk42ue03_3006.zip](https://github.com/TheImagingSource/tcam-firmware-update/files/13899431/dfk42ue03_3006.zip)
I hope this works for you.

Stefan

**Comment by girgine** [comment]
Hi Stefan,
Just did the update and it works like a charm! I can now see an 8 bit layer GRGR/BGBG as well as 8 bit Grayscale! using v4l2 and connects without any issues, YAY!

Thanks for the help and the file. :)
eg
